### ISSUE TITLE
这个主题适配2.0了吗？

### ISSUE THREAD

**Issue by LANGJIALINGBOJUE** [shuTwT/halo-theme-simpleBootstrap-next#1]
这个主题适配2.0了吗？我在halo官方的2.0演示站点安装不成功主题。
![image](https://github.com/shuTwT/halo-theme-simpleBootstrap-next/assets/42342530/19d960ef-e537-420b-b423-9973e11b65a2)

**Comment by shuTwT** [comment]
<img width="318" alt="屏幕截图 2024-02-19 104216" src="https://github.com/shuTwT/halo-theme-simpleBootstrap-next/assets/95295076/ddd8125c-28c7-47b8-82c5-4eb753d2a0fa">
<img width="504" alt="屏幕截图 2024-02-19 104259" src="https://github.com/shuTwT/halo-theme-simpleBootstrap-next/assets/95295076/fcf5a98b-8fe7-4b1d-b003-04d32eaf0539">

**Comment by shuTwT** [comment]
请下载压缩包而不是网页
